theme: jekyll-theme-minimal
title: .NET Dialog Service
description: Cross-platform system dialogs
logo: https://raw.githubusercontent.com/DialogService/DialogService.Media/master/DialogService%20Logo.png
github:
  is_user_page: false
  is_project_page: true
  repository_url: https://github.com/DialogService
  repository_nwo: https://github.com/DialogService
